### ISSUE TITLE
GIF Demo for Citii

### ISSUE THREAD

**Issue by djirdehh** [djirdehh/react-living-app#1]
![citii_app](https://cloud.githubusercontent.com/assets/12476938/22228725/fcdda7d6-e1a0-11e6-8295-55d5d4a57f5e.gif)

**Comment by djirdehh** [comment]
![citii-mobile](https://cloud.githubusercontent.com/assets/12476938/22230928/7421f5ce-e1ae-11e6-8c9e-02d6d14842fe.png)

**Comment by djirdehh** [comment]
https://gfycat.com/FrightenedClassicGourami

**Comment by djirdehh** [comment]
![citii-mobile](https://cloud.githubusercontent.com/assets/12476938/22233667/d440002a-e1bf-11e6-903b-21fedb84c1c3.png)

**Comment by djirdehh** [comment]
https://gfycat.com/SickJitteryDesertpupfish

**Comment by housseindjirdeh** [comment]
Another hosting place I use is Giphy but anyone would do really

**Comment by djirdehh** [comment]
![dallas_stock](https://cloud.githubusercontent.com/assets/12476938/22360991/6b902468-e423-11e6-8962-c6a6f0af58fb.png)

**Comment by djirdehh** [comment]
![dallas_stock](https://cloud.githubusercontent.com/assets/12476938/22361037/b57b7aa0-e423-11e6-9aea-a208599d4599.png)

**Comment by djirdehh** [comment]
![dallas_stock](https://cloud.githubusercontent.com/assets/12476938/22361063/13cd8170-e424-11e6-883e-76835aba3d7d.png)

**Comment by djirdehh** [comment]
![dallas-stock](https://cloud.githubusercontent.com/assets/12476938/22361089/67333896-e424-11e6-8acf-7287fac4e79d.png)

**Comment by djirdehh** [comment]
<img width="553" alt="screen shot 2017-01-27 at 12 07 08 am" src="https://cloud.githubusercontent.com/assets/12476938/22361107/9bc99d8e-e424-11e6-8327-0c5d31f5ca15.png">
