### ISSUE TITLE
Putting same city for living in and wanting to live in returns undefined

### ISSUE THREAD

**Issue by ericbastarache** [djirdehh/react-living-app#2]
If you select the same city for Current living (i.e Aachen, Germany) and run a comparison against Aachen, Germany, you get an undefined value for each of the categories (Rent, Groceries, Dining Out, Purchasing Power)

The following are images of the above: 

[Rent](https://gyazo.com/206b842b09e0b523fd293c4768ff6544)
[Groceries](https://gyazo.com/9fa60c47ea314d3e2d2d588be06a34d8)
[Dining Out](https://gyazo.com/b5add52051903fe265ce513ea078df42)
[Purchasing Power](https://gyazo.com/015075e2ba027f75e1e38b64ae273ec6)

Have only tested on 2 cities thus far (Aachen, Germany & Toronto, Canada) but I believe the above happens to each i f you input them twice.

**Comment by djirdehh** [comment]
Thanks @ericbastarache! For now, I just made a simple fix to say 'the values are the same'. I might modify it later and prevent the user from moving to the same city he's already living in.
